name: ci-command
on:
  repository_dispatch:
    types: [ci-command]
jobs:
  rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Setup branch
        id: setup-branch
        run: |
          pr_ref="${{ github.event.client_payload.pull_request.head.ref }}"
          branch_arg="${{ github.event.client_payload.slash_command.args.named.branch }}"
          branch="${branch_arg:-$pr_ref}"
          echo "pr ref is $pr_ref"
          echo "branch arg is $branch_arg"
          echo "branch is $branch"
          echo "::set-output name=branch::$branch"

      - name: Help
        if: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 == 'help' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            > Use the command as follows
            > /ci help # prints this help
            > /ci device # creates a device build for the current branch
            > • you can optionally pass in branch /ci device branch=some-branch
            > /ci automation # creates an automation build for the current branch
            > • you can optionally pass in branch /ci device branch=some-branch

      - name: Device Build
        if: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 == 'device' }}
        uses: scoremedia/workflow-dispatch@v1
        with:
          workflow: Device Build
          token: ${{ secrets.BOT_TOKEN }}
          inputs: '{"branch":"${{ steps.setup-branch.branch }}"}'
          ref: ${{ steps.setup-branch.branch }}

      - name: Automation Build
        if: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 == 'automation' }}
        uses: scoremedia/workflow-dispatch@v1
        with:
          workflow: CI
          token: ${{ secrets.BOT_TOKEN }}
          inputs: '{"branch":"${{ steps.setup-branch.branch }}","automation-build":"true"}'
          ref: ${{ steps.setup-branch.branch }}

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray